import { requireDateRange, requirePositiveId } from '../models/validation.js';

export class FinanzasRepository {
 constructor(pool){this.pool=pool;}
 async registrar(m){const c=await this.pool.getConnection();try{await c.beginTransaction();if(m.contrato_id){const [contratos]=await c.execute('SELECT cliente_id,estado FROM contratos WHERE id=? FOR UPDATE',[m.contrato_id]);if(!contratos.length)throw new Error('Contrato no encontrado.');if(contratos[0].estado!=='ACTIVO')throw new Error('No se pueden registrar movimientos en un contrato inactivo.');if(m.cliente_id&&Number(m.cliente_id)!==contratos[0].cliente_id)throw new Error('El contrato no pertenece al cliente indicado.');m.cliente_id=contratos[0].cliente_id;}const [r]=await c.execute('INSERT INTO movimientos(cliente_id,contrato_id,tipo,concepto,monto,fecha,creado_por) VALUES(?,?,?,?,?,?,?)',[m.cliente_id,m.contrato_id,m.tipo,m.concepto,m.monto,m.fecha,m.creado_por]);await c.commit();return r.insertId;}catch(e){await c.rollback();throw e;}finally{c.release();}}
 construirFiltros({desde=null,hasta=null,clienteId=null}={}){const rango=requireDateRange({desde,hasta});const filtros=[],valores=[];if(rango.desde){filtros.push('fecha>=?');valores.push(rango.desde);}if(rango.hasta){filtros.push('fecha<=?');valores.push(rango.hasta);}if(clienteId!==null&&clienteId!==undefined&&clienteId!==''){filtros.push('cliente_id=?');valores.push(requirePositiveId(clienteId,'El cliente'));}return {where:filtros.length?` WHERE ${filtros.join(' AND ')}`:'',valores};}
 async listar(filtros={}){const {where,valores}=this.construirFiltros(filtros);const [r]=await this.pool.execute(`SELECT * FROM movimientos${where} ORDER BY fecha DESC,id DESC`,valores);return r;}
 async balance(filtros={}){const {where,valores}=this.construirFiltros(filtros);const [r]=await this.pool.execute(`SELECT COALESCE(SUM(CASE WHEN tipo='INGRESO' THEN monto ELSE 0 END),0) AS ingresos,COALESCE(SUM(CASE WHEN tipo='EGRESO' THEN monto ELSE 0 END),0) AS egresos FROM movimientos${where}`,valores);const ingresos=Number(r[0].ingresos),egresos=Number(r[0].egresos);return {ingresos,egresos,balance:ingresos-egresos};}
}
